### ISSUE TITLE
require() does not work, but library() does

### ISSUE THREAD

**Issue by mcmullenhjack** [tbrown122387/gradeR#12]
When loading in a package using, for example, require(stringr), the autograder does not recognize the function. However, when using library(stringr), it works just fine. Both functions perform the same action, thus they should both work.

**Comment by tbrown122387** [comment]
@mcmullenhjack I was calling `tryCatch` in the `callr::r` subprocess, and not in the main process. I've read [this](https://www.tidyverse.org/blog/2019/07/callr-3.3.0/), and I think I've fixed this, but if you notice it on any new assignment, let me know. In the meantime I'm closing the issue.
