### ISSUE TITLE
GradeR not loading tidyverse?

### ISSUE THREAD

**Issue by davbachman** [tbrown122387/gradeR#21]
I now have a colleague using all my old assignments and autograders. They worked great for him last year but now they stopped. 

One line of the setup.sh code that he was using was this:
Rscript -e "install.packages('devtools'); devtools::install_github('tbrown122387/gradeR’)"

That came from an old exchange with you when I was having some trouble implementing something. I don’t know if this line of code is what is now causing issues, but my colleague is getting an error from Gradescope that says “library gradeR not found”.

I had him change the above setup.sh code to this instead:
Rscript -e "install.packages('gradeR')"

And the error changed to: 

“Error: library(tidy verse)”
NULL

However, my setup file does include this line:
Rscript -e "install.packages('tidyverse')"

Any help you can give us would be appreciated!

Zip file attached. 

[Archive.zip](https://github.com/tbrown122387/gradeR/files/14103386/Archive.zip)

**Comment by tbrown122387** [comment]
If you look at the build output in Gradescope, you'll see the `setup.sh` file fails to install `tidyverse`. I won't copy/paste the entire output, but I spotted a few "ERROR" messages:

```
ERROR: configuration failed for package ‘systemfonts’
ERROR: dependency ‘systemfonts’ is not available for package ‘textshaping’
ERROR: dependencies ‘systemfonts’, ‘textshaping’ are not available for package ‘ragg’
ERROR: dependency ‘ragg’ is not available for package ‘tidyverse’
``` 

You'll need to add some `apt-get` lines to `setup.sh`. See [here](https://community.rstudio.com/t/tidyverse-package-does-not-install/162507/3) for more info

**Comment by davbachman** [comment]
OK, that helped. Added several apt-get lines. No errors on compilation now, and tidyverse loads. However, things still aren't working right: it graded every problem as incorrect (they're not)! New zip file attached. 
[Archive.zip](https://github.com/tbrown122387/gradeR/files/14108275/Archive.zip)

**Comment by tbrown122387** [comment]
In the file `run_autograder` try changing the last line from 
```
Rscript grade_one_submission_hw2.R
```
to 
```
LC_ALL= Rscript grade_one_submission.r
```

If that works *please let me know.* Same thing happened to me. Note that that command is space sensitive

**Comment by davbachman** [comment]
Almost! It graded all problems correctly except for two of them. (I'll double check those solutions.)
