### ISSUE TITLE
Contact at GradeScope??

### ISSUE THREAD

**Issue by lewkrr** [tbrown122387/gradeR#7]
Just curious who you worked with at GradeScope to develop the `calcGradesForGradescope()` function?  I want to learn more about the gradeR package and my university support using GradeScope.

**Comment by tbrown122387** [comment]
Technically this is a ["community resource,"](https://github.com/gradescope/autograder_samples/blob/master/docs/resources.md) meaning this isn't an "official" example sanctioned by Gradescope. The official examples from Gradescope can be found in their documentation ([click here.](https://gradescope-autograders.readthedocs.io/en/latest/)) This is probably going to be the most informative resource. 

Personally, I found the [other R autograder](https://github.com/guerzh/r_autograde_gradescope) in the community resources to be very helpful, as well. As far as I can tell, there is no official R example, yet.
